
#groups


QRING_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/QScign/QRing
RELAE_GRAPH_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/hgdm/relae-graph
PHAON_GRAPH_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/hgdm/phaon-graph
NTXH_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/hgdm/ntxh
DSMAIN_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/dataset/dsmain
SSQM_DSMAIN_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/ssqm/ssqm-dsmain
XPDF_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/xk/external/xpdf
APPLICATION_MODEL_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/dataset/application-model
CONFIG_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/dataset/config
PHR_GRAPH_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/hgdm/phr-graph
RELAE_GRAPH_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/hgdm/relae-graph
PHAONIR_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/sk/phaonir/PhaonIR
PHAONLIB_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/sk/phaonir/PhaonLib
PHR_RUNTIME_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/sk/phaonir/phr-runtime
TESTS_PHR_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/sk/rz/tests-phr
WHITEDB_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/dbk/whitedb/whitedb

RZ_KAUVIR_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/sk/rz/rz-kauvir

IAT_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/xk/iat/iat
IAT_MODEL_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/xk/iat/iat-model

AIMLIB_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/xk/aim/aimlib

QUA_ZIP_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/xk/external/quazip
DCMTK_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/xk/external/dcmtk

ANGELSCRIPT_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/xk/external/angelscript

SCIGNSTAGE_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/QScign/ScignStage

DGDB_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/dbk/dgdb/dgdb


HTXN_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/htxn/htxn
MPF_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/htxn/mosaic
CWL_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/xk/external/cwl
GTAGML_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/imk/gtagml/gtagml

DGDB_WHITE_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/dbk/dgdb/dgdb-white

DGH_SDI_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/dbk/dgdb/dgh-sdi

LEXPAIR_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/QScign/LexPair

QHP_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/dbk/dgdb/qhp

CHASM_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/apk/hgdm/chasm

XCSD_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/imk/xcsd/xcsd-2d
XCSD_DATA_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/imk/xcsd/xcsd-data
XCSD_GUI_SRC_GROUP_DIR = $$SRC_CONTRIB_DIR/imk/xcsd/xcsd-gui

